language: cpp

os: linux

matrix:
  include:
    # Windows
    - os: "windows"
      compiler: "clang"

    # OSX
    - env: COMPILER=clang++ BUILD_TYPE=Release GSL_CXX_STANDARD=14
      os: "osx"
      compiler: clang
      
    # Ubuntu
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - clang++-6.0
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-8
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - arch: "arm64"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-8
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  eval ${MATRIX_EVAL}

install: 
  - echo "INSTALL"
  - pwd
  - ls

  - git clone https://github.com/google/googletest googletest/
  - cd googletest
  - if [ $TRAVIS_OS_NAME = 'windows' ] || [ $TRAVIS_OS_NAME = 'osx' ]; then cmake -DBUILD_SHARED_LIBS=ON --config Release .; fi
  - if [ $TRAVIS_OS_NAME = 'linux' ]; then cmake --config Release .; fi
  - cmake --build . --config Release
  - if [ $TRAVIS_OS_NAME = 'osx' ] || [ $TRAVIS_OS_NAME = 'linux' ]; then sudo make install; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then cmake --build . --target install; fi
  - cd ..

  - if [ $TRAVIS_OS_NAME = 'windows' ]; then ls googletest/lib/Release/ ; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then ls googletest/googletest/ ; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then find -name "*.dll"; fi
#  - if [ $TRAVIS_OS_NAME = 'linux' ]; then find -name "*.so"; fi

  - echo `pwd`
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then cp googletest/bin/Release/gtest.dll .; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then cp googletest/lib/Release/gtest.lib .; fi
  #- if [ $TRAVIS_OS_NAME = 'linux' ]; then cp googletest/lib/libgtest.so .; fi
  #- if [ $TRAVIS_OS_NAME = 'linux' ]; then set LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH; fi
  
script:
  - echo "SCRIPT"
  - pwd
  - ls

  - cmake --version
  - cmake .
  - cmake --build .
  - if [ $TRAVIS_OS_NAME = 'linux' ] || [ $TRAVIS_OS_NAME = 'osx' ]; then sudo make install; fi
#  - if [ $TRAVIS_OS_NAME = 'windows' ]; then cmake --build . --target install; fi
  - if [ $TRAVIS_OS_NAME != 'windows' ]; then ./igris_test; fi
  - if [ $TRAVIS_OS_NAME != 'windows' ]; then ctest .; fi