language: cpp

os: linux

matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - clang++-6.0
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - os: "osx"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - clang++-6.0
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-8
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-7
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-6
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - clang++-7.0
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7.0"

before_install:
  eval ${MATRIX_EVAL}

install: 
  - mkdir ~/gtest && cd ~/gtest
  - export LIBRARY_PATH=$(pwd)
  - cp -r /usr/src/gtest/* ./
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
  - make
  - mkdir include && cp -r /usr/include/gtest include
  - mkdir lib && cp libgtest* lib
  - cd -

script:
  - export GTEST_COLOR=1
  - export GTEST_ROOT="~/gtest"
  - cmake --version
  - cmake CMakeLists.txt
  - make
  - make test