language: cpp

os: linux

matrix:
  include:
    # Windows
    - os: "windows"
      compiler: "clang"

    # OSX
    - os: "osx"
      compiler: clang
      
    # Ubuntu
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - clang++-6.0
      env:
         - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - arch: "arm64"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  eval ${MATRIX_EVAL}

install: 
  - echo "INSTALL"
  - pwd
  - ls

  - git clone https://github.com/google/googletest googletest/
  - cd googletest
  - cmake -DBUILD_SHARED_LIBS=ON --config Release .
  - cmake --build . --config Release
  - if [ $TRAVIS_OS_NAME = 'osx' || $TRAVIS_OS_NAME = 'linux' ]; then sudo make install; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then cmake --build . --target install; fi
  - cd ..

  - if [ $TRAVIS_OS_NAME = 'windows' ]; then ls googletest/lib/Release/ ; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then ls googletest/googletest/ ; fi
  - find -name "*.dll"
  - find -name "*.so"

  - echo `pwd`
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then cp googletest/bin/Release/gtest.dll .; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then cp googletest/lib/Release/gtest.lib .; fi
  - if [ $TRAVIS_OS_NAME = 'linux' ] || [ $TRAVIS_OS_NAME = 'osx' ]; then cp googletest/googletest/gtest.so .; fi
  
script:
  - echo "SCRIPT"
  - pwd
  - ls

  - cmake --version
  - cmake .
  - cmake --build .
  - if [ $TRAVIS_OS_NAME = 'linux' ] || [ $TRAVIS_OS_NAME = 'osx' ]; then sudo make install; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then cmake --build . --target install; fi
  - ctest .