language: cpp

os: linux

matrix:
  include:
    - os: "osx"
      compiler: clang
      
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - clang++-6.0
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-8
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - arch: "arm64"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-8
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - os: "windows"
      compiler: "clang"

before_install:
  eval ${MATRIX_EVAL}

install: 
  - echo "INSTALL"
  - pwd
  - ls

  - git clone https://github.com/google/googletest googletest/
  - cd googletest
  - cmake .
  - cmake --build .
  - if [ $TRAVIS_OS_NAME = 'linux' || $TRAVIS_OS_NAME = 'macosx' ]; then sudo -E cmake --build . --target install; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then cmake --build . --target install; fi
  
  - cd ..

script:
  - echo "SCRIPT"
  - pwd
  - ls

  - cmake --version
  - cmake .
  - cmake --build .
  - if [ $TRAVIS_OS_NAME = 'linux' || $TRAVIS_OS_NAME = 'macosx' ]; then sudo -E cmake --build . --target install; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then cmake --build . --target install; fi
  - ctest .