language: cpp

os: linux

matrix:
  include:
    - os: "osx"
      compiler: clang
      
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - clang++-6.0
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-8
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  eval ${MATRIX_EVAL}

install: 
  - echo "INSTALL"
  - pwd
  - ls

  - mkdir ~/gtest && cd ~/gtest
  - export LIBRARY_PATH=$(pwd)

  - git clone https://github.com/google/googletest googletest/
  - cd googletest
  - cmake . -DBUILD_SHARED_LIBS=ON
  - make
  
  - cd ~

script:
  - echo "SCRIPT"
  - pwd
  - ls

  - cp googletest/lib/* .
  - cp -r googletest/googletest/include/gtest igris/

  - cmake --version
  - cmake CMakeLists.txt
  - make
  - make test