language: cpp

os: linux

matrix:
  include:
    - os: "osx"
      compiler: clang
      
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - clang++-6.0
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-8
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  eval ${MATRIX_EVAL}

install: 

  - mkdir ~/gtest && cd ~/gtest
  - export LIBRARY_PATH=$(pwd)

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    git clone https://github.com/google/googletest
    cd googletest
  fi

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    cp -r /usr/src/gtest/* ./
  fi
  
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
  - make
  - mkdir include && cp -r /usr/include/gtest include
  - mkdir lib && cp libgtest* lib
  - cd ~

script:
  - export GTEST_COLOR=1
  - export GTEST_ROOT="~/gtest"
  - cmake --version
  - cmake CMakeLists.txt
  - make
  - make test