language: cpp

os: linux

matrix:
  include:
    # Windows
    - os: "windows"
      compiler: "clang"

    # OSX
    - os: "osx"
      compiler: clang
      
    # Ubuntu
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - clang++-6.0
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-8
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - arch: "arm64"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-8
           - libgtest-dev
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
  eval ${MATRIX_EVAL}

install: 
  - echo "INSTALL"
  - pwd
  - ls

  - git clone https://github.com/google/googletest googletest/
  - cd googletest/googletest
  - cmake -DBUILD_SHARED_LIBS=ON .
  - cmake --build .
  - if [ $TRAVIS_OS_NAME = 'linux' ] || [ $TRAVIS_OS_NAME = 'osx' ]; then sudo make install; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then cmake --build . --target install; fi
  - ls
  - ls googletest
  - ls googlemock
  - ls lib

  - cd ../..
  - echo `pwd`
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then export "PATH=`pwd`/googletest/googletest/:$PATH"; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then export "INCLUDE=`pwd`/googletest/googletest/include:$INCLUDE"; fi
  - echo $PATH
  - echo $INCLUDE

script:
  - echo "SCRIPT"
  - pwd
  - ls

  - cmake --version
  - cmake .
  - cmake --build .
  - if [ $TRAVIS_OS_NAME = 'linux' ] || [ $TRAVIS_OS_NAME = 'osx' ]; then sudo make install; fi
  - if [ $TRAVIS_OS_NAME = 'windows' ]; then cmake --build . --target install; fi
  - ctest .