language: cpp
compiler: gcc

os: linux
dist: trusty

matrix:
  include:
    # GCC 7
    - env: COMPILER=g++-7 BUILD_TYPE=Debug GSL_CXX_STANDARD=14
      addons: &gcc7
        apt:
          packages: g++-7
          sources:
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-7 BUILD_TYPE=Release GSL_CXX_STANDARD=14
      addons: *gcc7

    # GCC 7 c++17 
    - env: COMPILER=g++-7 BUILD_TYPE=Debug GSL_CXX_STANDARD=17
      addons: *gcc7

    - env: COMPILER=g++-7 BUILD_TYPE=Release GSL_CXX_STANDARD=17
      addons: *gcc7

install: 
  - mkdir ~/gtest && cd ~/gtest
  - export LIBRARY_PATH=$(pwd)
  - cp -r /usr/src/gtest/* ./
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
  - make
  - mkdir include && cp -r /usr/include/gtest include
  - mkdir lib && cp libgtest* lib
  - cd -

script:
  - export GTEST_COLOR=1
  - export GTEST_ROOT="~/gtest"
  - cmake --version
  - cmake CMakeLists.txt
  - make
  - make test